DROP TABLE IF EXISTS MatchupTeam;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Team;
DROP TABLE IF EXISTS Matchup;
DROP TABLE IF EXISTS Tournament;
DROP TABLE IF EXISTS TournamentType;
DROP TABLE IF EXISTS GameType;
DROP TABLE IF EXISTS Users;


CREATE TABLE Users (
	UserID INT NOT NULL PRIMARY KEY,
	Username VARCHAR (30) NOT NULL,
	PasswordHash VARCHAR (30) NOT NULL,
	Salt VARCHAR (30) NOT NULL
);

CREATE TABLE GameType (
	GameTypeId INT NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	TeamsPerMatch INT NOT NULL,
	PointsForDraw INT NOT NULL,
	PointsForWin INT NOT NULL
);

CREATE TABLE TournamentType (
	TournamentTypeId INT NOT NULL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE Tournament (
	TourneyID INT NOT NULL PRIMARY KEY,
	GameTypeId INT NOT NULL,
	UserID INT NOT NULL,
	TypeId INT NOT NULL,
	StartDate DATE NOT NULL,
	FOREIGN KEY (UserID) REFERENCES Users(UserID),
	FOREIGN KEY (GameTypeId) REFERENCES GameType(GameTypeId),
	FOREIGN KEY (TypeId) REFERENCES TournamentType(TournamentTypeId)
);

CREATE TABLE Matchup (
	MatchupID INT NOT NULL PRIMARY KEY,
	Rounds INT NOT NULL,
	TourneyID INT NOT NULL,
	NextMatchupId INT,
	FOREIGN KEY (NextMatchupId) REFERENCES Matchup(MatchupID),
	FOREIGN KEY (TourneyID) REFERENCES Tournament(TourneyID)
);

CREATE TABLE Team (
	TeamID INT NOT NULL PRIMARY KEY,
	TeamName VARCHAR (30) NOT NULL
);

CREATE TABLE Player (
	PlayerID INT NOT NULL PRIMARY KEY,
	TeamID INT NOT NULL,
	FirstName VARCHAR (30) NOT NULL,
	LastName VARCHAR (30) NOT NULL,
	FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
);

CREATE TABLE MatchupTeam (
	MatchupTeamID INT NOT NULL PRIMARY KEY,
	TeamID INT NOT NULL,
	MatchupID INT NOT NULL,
	Score INT,
	FOREIGN KEY (TeamID) REFERENCES Team(TeamID),
	FOREIGN KEY (MatchupID) REFERENCES Matchup(MatchupID)
);

	
	