USE TourneyPlannerDev;

DROP TABLE IF EXISTS [User];
DROP TABLE IF EXISTS GameType;
DROP TABLE IF EXISTS TournamentType;
DROP TABLE IF EXISTS Tournament;
DROP TABLE IF EXISTS Matchup;
DROP TABLE IF EXISTS Team;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS MatchupTeam;
DROP TABLE IF EXISTS ;


CREATE TABLE [User] (
	Id INT NOT NULL PRIMARY KEY,
	Email VARCHAR(100) NOT NULL,
	PasswordHash VARCHAR(100) NOT NULL,
	Salt VARCHAR(32) NOT NULL
);

CREATE TABLE GameType (
	Id INT NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	TeamsPerMatch INT NOT NULL,
	PointsForDraw INT NOT NULL,
	PointsForWin INT NOT NULL
);

CREATE TABLE TournamentType (
	Id INT NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Tournament (
	Id INT NOT NULL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	GameTypeId INT NOT NULL,
	TournamentTypeId INT NOT NULL,
	UserId INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES [User](Id),
	FOREIGN KEY (GameTypeId) REFERENCES GameType(Id),
	FOREIGN KEY (TournamentTypeId) REFERENCES TournamentType(Id)
);

CREATE TABLE Matchup (
	Id INT NOT NULL PRIMARY KEY,
	StartDateTime DATETIME NOT NULL,
	Rounds INT NOT NULL,
	TournamentId INT NOT NULL,
	NextMatchupId INT,
	FOREIGN KEY (NextMatchupId) REFERENCES Matchup(Id),
	FOREIGN KEY (TournamentId) REFERENCES Tournament(Id)
);

CREATE TABLE Team (
	Id INT NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE Player (
	Id INT NOT NULL PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR (50) NOT NULL,
	TeamId INT NOT NULL,
	FOREIGN KEY (TeamId) REFERENCES Team(Id)
);

CREATE TABLE MatchupTeam (
	Id INT NOT NULL PRIMARY KEY,
	Score INT,
	TeamId INT NOT NULL,
	MatchupId INT NOT NULL,
	FOREIGN KEY (TeamId) REFERENCES Team(Id),
	FOREIGN KEY (MatchupId) REFERENCES Matchup(Id)
);

CREATE TABLE FavoritMatchup (
	Id INT NOT NULL PRIMARY KEY,
	MatchupId INT NOT NULL,
	UserId INT NOT NULL,
	FOREIGN KEY (MatchupId) REFERENCES Matchup(Id),
	FOREIGN KEY (UserId) REFERENCES [User](Id)
);