name: tourney_planner
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^15.1.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  form_field_validator: ^1.1.0
  get_it: ^7.6.4
  graphview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - 'assets/localhost+3-client.p12'
    - 'assets/localhost+3-key.pem'
    - 'assets/localhost+3.pem'
    - 'assets/logo.png'
